# Config file for automatic testing at travis-ci.com

dist: focal
language: python
cache:
    pip: true
    directories:
        - $HOME/.cache/pypoetry
        - $HOME/.cache/pre-commit

python:
    - 3.11
    - 3.10
    - 3.9
    - 3.8

branches:
    only:
        - master
        - /v\d+\.\d+\.\d+/

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

deploy:
    provider: pypi
    distributions: sdist bdist_wheel
    username: __token__
    password: $PYPI_PASSWORD
    edge: true
    skip_existing: true
    on:
        tags: true
        repo: pymetrics/pact-testgen
        python: 3.8
