#!/usr/bin/env bash

# This is silly, but MacOS doesn't have realpath
HERE=(`python -c "import os, sys; print(os.path.dirname(os.path.abspath('$0')))"`)

pact-testgen pactfiles/LibraryClient-Library-pact.json  $HERE/provider/tests --debug
