#!/usr/bin/env bash

# This is silly, but MacOS doesn't have realpath
HERE=(`python -c "import os, sys; print(os.path.dirname(os.path.abspath('$0')))"`)

echo `which pact-testgen`

pact-testgen \
    $HERE/provider/tests \
    --merge-provider-state-file \
    --pact-file $HERE/pactfiles/LibraryClient-Library-pact.json \
    --debug
